name: C:\Users\Chengqian\desktop\Gpu\env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiofiles=22.1.0
  - annotated-types=0.6.0
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - catalogue=2.0.10
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - confection=0.1.4
  - contourpy=1.3.1
  - cryptography=43.0.3
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=1.0.1
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.4.2
  - email-validator=2.2.0
  - email_validator=2.2.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fastapi=0.115.6
  - fastapi-cli=0.0.7
  - fastdownload=0.0.7
  - ffmpeg=6.1.1
  - ffmpy=0.3.0
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=4.3.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=2.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - langcodes=3.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mistune=3.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - murmurhash=1.0.7
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orjson=3.10.14
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - preshed=3.0.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydub=0.25.1
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pywin32=308
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - referencing=0.36.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - safehttpx=0.1.6
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - semantic_version=2.8.5
  - send2trash=1.8.3
  - setuptools=75.1.0
  - shellingham=1.5.0
  - six=1.17.0
  - smart-open=7.1.0
  - smart_open=7.1.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.6.3
  - starlette=0.41.3
  - tbb=2021.8.0
  - terminado=0.18.1
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wasabi=0.9.1
  - watchdog=4.0.1
  - watchfiles=0.24.0
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=10.4
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - altair==5.5.0
      - astatine==0.3.3
      - astroid==2.5
      - attr-utils==1.1.0
      - beartype==0.21.0
      - branca==0.8.1
      - brotli==1.1.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - consolekit==1.7.2
      - datasets==3.2.0
      - ddgs==9.5.2
      - deepl==1.22.0
      - deprecation==2.1.0
      - deprecation-alias==0.3.3
      - dill==0.3.8
      - distro==1.9.0
      - dom-toml==2.0.0
      - domdf-python-tools==3.9.0
      - duckduckgo-search==8.1.1
      - emoji==2.14.1
      - empath==0.89
      - fastai==2.8.4
      - fastcore==1.8.8
      - fastkaggle==0.0.8
      - fastprogress==1.0.3
      - fasttransform==0.0.2
      - folium==0.20.0
      - formate==0.7.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - geodatasets==2024.8.0
      - geographiclib==2.0
      - geopandas==1.1.1
      - geopy==2.4.1
      - ghapi==1.0.5
      - gradio==5.42.0
      - gradio-client==1.11.1
      - graphviz==0.20.3
      - groovy==0.1.2
      - huggingface-hub==0.34.4
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isort==5.13.2
      - jiter==0.9.0
      - joblib==1.5.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.4
      - jupyterlab==4.4.1
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - lazy-object-proxy==1.10.0
      - lxml==5.3.1
      - mccabe==0.6.1
      - mistletoe==1.4.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - narwhals==1.22.0
      - natsort==8.4.0
      - nbclassic==1.3.1
      - notebook==7.4.1
      - notebook2script==0.2.1
      - numpy==2.0.2
      - openai==1.93.0
      - patsy==1.0.2
      - pillow==10.4.0
      - pip==25.2
      - plotly==6.2.0
      - plum-dispatch==2.5.7
      - pooch==1.8.2
      - pre-commit-hooks==5.0.0
      - prettyprinter==0.18.0
      - primp==0.15.0
      - propcache==0.2.1
      - protobuf==5.29.3
      - pyarrow==19.0.0
      - pylint==2.7.1
      - pyogrio==0.11.0
      - pyproj==3.7.1
      - python-slugify==8.0.4
      - regex==2024.11.6
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - ruff==0.12.8
      - safetensors==0.5.2
      - seaborn==0.13.2
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - shapely==2.1.1
      - stanza==1.10.1
      - statsmodels==0.14.6
      - sympy==1.13.1
      - text-unidecode==1.3
      - tiktoken==0.8.0
      - timm==1.0.14
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomlkit==0.12.0
      - toolz==1.0.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - transformers==4.48.1
      - widgetsnbextension==4.0.13
      - wrapt==1.12.1
      - xgboost==3.0.2
      - xxhash==3.5.0
      - xyzservices==2025.4.0
      - yapf==0.43.0
      - yapf-isort==0.7.0
      - yarl==1.18.3
prefix: C:\Users\Chengqian\desktop\Gpu\env
